package model

type (
	Country struct {
		Name   string
		Cities map[string]List
	}

	City struct {
		Base
		Name     string `gorm:"unique_index:city"`
		Province string `gorm:"unique_index:city"`
		Country  string `gorm:"unique_index:city"`
	}
)

var (
	Angola = Country{
		Name: "Angola",
		Cities: map[string]List{
			"Bengo":          List{},
			"Benguela":       List{},
			"Bié":            List{},
			"Cabinda":        List{},
			"Cuando Cubango": List{},
			"Cuanza Norte":   List{},
			"Cuanza Sul":     List{},
			"Cunene":         List{},
			"Huambo":         List{},
			"Huíla":          List{},
			"Luanda":         List{},
			"Lunda Norte":    List{},
			"Lunda Sul":      List{},
			"Malanje":        List{},
			"Moxico":         List{},
			"Namibe":         List{},
			"Uíge":           List{},
			"Zaire":          List{},
		},
	}

	CountryNames = List{
		"Afeganistão",
		"Akrotiri",
		"Albânia",
		"Argélia",
		"Samoa Americana",
		"Andorra",
		"Angola",
		"Anguilla",
		"Antártica",
		"Antígua e Barbuda",
		"Argentina",
		"Armênia",
		"Aruba",
		"Ilhas Ashmore e Cartier",
		"Austrália",
		"Áustria",
		"Azerbaijão",
		"Bahamas, The",
		"Barém",
		"Bangladesh",
		"Barbados",
		"Bassas da India",
		"Bielorrússia",
		"Bélgica",
		"Belize",
		"Benin",
		"Bermudas",
		"Butão",
		"Bolívia",
		"Bósnia e Herzegovina",
		"Botsuana",
		"Ilha Bouvet",
		"Brasil",
		"Território Britânico do Oceano Índico",
		"Ilhas Virgens Britânicas",
		"Brunei",
		"Bulgária",
		"Burkina Faso",
		"Birmânia",
		"Burundi",
		"Camboja",
		"Camarões",
		"Canadá",
		"cabo Verde",
		"Ilhas Cayman",
		"República Centro-Africana",
		"Chade",
		"Chile",
		"China",
		"Ilha do Natal",
		"Clipperton Island",
		"Ilhas Cocos (Keeling)",
		"Colômbia",
		"Comores",
		"Congo, República Democrática do",
		"República do Congo",
		"Ilhas Cook",
		"Ilhas do Mar de Coral",
		"Costa Rica",
		"Costa do Marfim",
		"Croácia",
		"Cuba",
		"Chipre",
		"República Checa",
		"Dinamarca",
		"Dhekelia",
		"Djibuti",
		"Dominica",
		"República Dominicana",
		"Equador",
		"Egito",
		"El Salvador",
		"Guiné Equatorial",
		"Eritreia",
		"Estônia",
		"Etiópia",
		"Europa Island",
		"Ilhas Malvinas (Ilhas Malvinas)",
		"ilhas Faroe",
		"Fiji",
		"Finlândia",
		"França",
		"Guiana Francesa",
		"Polinésia Francesa",
		"Terras Austrais e Antárticas Francesas",
		"Gabão",
		"Gâmbia, The",
		"faixa de Gaza",
		"Geórgia",
		"Alemanha",
		"Gana",
		"Gibraltar",
		"Ilhas Glorioso",
		"Grécia",
		"Gronelândia",
		"Granada",
		"Guadalupe",
		"Guam",
		"Guatemala",
		"Guernsey",
		"Guiné",
		"Guiné-Bissau",
		"Guiana",
		"Haiti",
		"Ilha Heard e Ilhas McDonald",
		"Santa Sé (Cidade do Vaticano)",
		"Honduras",
		"Hong Kong",
		"Hungria",
		"Islândia",
		"Índia",
		"Indonésia",
		"Eu corri",
		"Iraque",
		"Irlanda",
		"Ilha de Man",
		"Israel",
		"Itália",
		"Jamaica",
		"Jan Mayen",
		"Japão",
		"Jersey",
		"Jordânia",
		"Ilha Juan de Nova",
		"Cazaquistão",
		"Quênia",
		"Kiribati",
		"Coreia do Norte",
		"Coreia do Sul",
		"Kuwait",
		"Quirguistão",
		"Laos",
		"Letônia",
		"Líbano",
		"Lesoto",
		"Libéria",
		"Líbia",
		"Liechtenstein",
		"Lituânia",
		"Luxemburgo",
		"Macau",
		"Macedônia",
		"Madagáscar",
		"Malawi",
		"Malásia",
		"Maldivas",
		"Mali",
		"Malta",
		"Ilhas Marshall",
		"Martinica",
		"Mauritânia",
		"Maurícia",
		"Mayotte",
		"México",
		"Micronésia, Estados Federados da",
		"Moldova",
		"Mônaco",
		"Mongólia",
		"Montserrat",
		"Marrocos",
		"Moçambique",
		"Namíbia",
		"Nauru",
		"Ilha Navassa",
		"Nepal",
		"Países Baixos",
		"Antilhas Holandesas",
		"Nova Caledônia",
		"Nova Zelândia",
		"Nicarágua",
		"Níger",
		"Nigéria",
		"Niue",
		"Ilha Norfolk",
		"Ilhas Marianas do Norte",
		"Noruega",
		"Omã",
		"Paquistão",
		"Palau",
		"Panamá",
		"Papua Nova Guiné",
		"Ilhas Paracel",
		"Paraguai",
		"Peru",
		"Filipinas",
		"Ilhas Pitcairn",
		"Polônia",
		"Portugal",
		"Porto Rico",
		"Catar",
		"Reunião",
		"Romênia",
		"Rússia",
		"Ruanda",
		"Santa Helena",
		"São Cristóvão e Nevis",
		"Santa Lúcia",
		"São Pedro e Miquelon",
		"São Vicente e Granadinas",
		"Samoa",
		"San Marino",
		"São Tomé e Príncipe",
		"Arábia Saudita",
		"Senegal",
		"Sérvia e Montenegro",
		"Seychelles",
		"Serra Leoa",
		"Cingapura",
		"Eslováquia",
		"Eslovênia",
		"Ilhas Salomão",
		"Somália",
		"África do Sul",
		"Ilhas Geórgia do Sul e Sandwich do Sul",
		"Espanha",
		"Ilhas Spratly",
		"Sri Lanka",
		"Sudão",
		"Suriname",
		"Svalbard",
		"Suazilândia",
		"Suécia",
		"Suíça",
		"Síria",
		"Taiwan",
		"Tajiquistão",
		"Tanzânia",
		"Tailândia",
		"Timor-Leste",
		"Ir",
		"Tokelau",
		"Tonga",
		"Trindade e Tobago",
		"Ilha de Tromelin",
		"Tunísia",
		"Peru",
		"Turquemenistão",
		"Ilhas Turcas e Caicos",
		"Tuvalu",
		"Uganda",
		"Ucrânia",
		"Emirados Árabes Unidos",
		"Reino Unido",
		"Estados Unidos",
		"Uruguai",
		"Usbequistão",
		"Vanuatu",
		"Venezuela",
		"Vietnã",
		"Ilhas Virgens",
		"Ilha Wake",
		"Wallis e Futuna",
		"Cisjordânia",
		"Saara Ocidental",
		"Iémen",
		"Zâmbia",
		"Zimbábue",
	}
)
