package util

var (
	Countries = map[string]Country{
		"AF": Country{Name: "Afghanistan", ISO2: "AF"},
		"AX": Country{Name: "ALA Aland Islands", ISO2: "AX"},
		"AL": Country{Name: "Albania", ISO2: "AL"},
		"DZ": Country{Name: "Algeria", ISO2: "DZ"},
		"AS": Country{Name: "American Samoa", ISO2: "AS"},
		"AD": Country{Name: "Andorra", ISO2: "AD"},
		"AO": Country{Name: "Angola", ISO2: "AO"},
		"AI": Country{Name: "Anguilla", ISO2: "AI"},
		"AQ": Country{Name: "Antarctica", ISO2: "AQ"},
		"AG": Country{Name: "Antigua and Barbuda", ISO2: "AG"},
		"AR": Country{Name: "Argentina", ISO2: "AR"},
		"AM": Country{Name: "Armenia", ISO2: "AM"},
		"AW": Country{Name: "Aruba", ISO2: "AW"},
		"AU": Country{Name: "Australia", ISO2: "AU"},
		"AT": Country{Name: "Austria", ISO2: "AT"},
		"AZ": Country{Name: "Azerbaijan", ISO2: "AZ"},
		"BS": Country{Name: "Bahamas", ISO2: "BS"},
		"BH": Country{Name: "Bahrain", ISO2: "BH"},
		"BD": Country{Name: "Bangladesh", ISO2: "BD"},
		"BB": Country{Name: "Barbados", ISO2: "BB"},
		"BY": Country{Name: "Belarus", ISO2: "BY"},
		"BE": Country{Name: "Belgium", ISO2: "BE"},
		"BZ": Country{Name: "Belize", ISO2: "BZ"},
		"BJ": Country{Name: "Benin", ISO2: "BJ"},
		"BM": Country{Name: "Bermuda", ISO2: "BM"},
		"BT": Country{Name: "Bhutan", ISO2: "BT"},
		"BO": Country{Name: "Bolivia", ISO2: "BO"},
		"BA": Country{Name: "Bosnia and Herzegovina", ISO2: "BA"},
		"BW": Country{Name: "Botswana", ISO2: "BW"},
		"BV": Country{Name: "Bouvet Island", ISO2: "BV"},
		"BR": Country{Name: "Brazil", ISO2: "BR"},
		"IO": Country{Name: "British Indian Ocean Territory", ISO2: "IO"},
		"VG": Country{Name: "British Virgin Islands", ISO2: "VG"},
		"BN": Country{Name: "Brunei Darussalam", ISO2: "BN"},
		"BG": Country{Name: "Bulgaria", ISO2: "BG"},
		"BF": Country{Name: "Burkina Faso", ISO2: "BF"},
		"BI": Country{Name: "Burundi", ISO2: "BI"},
		"KH": Country{Name: "Cambodia", ISO2: "KH"},
		"CM": Country{Name: "Cameroon", ISO2: "CM"},
		"CA": Country{Name: "Canada", ISO2: "CA"},
		"CV": Country{Name: "Cape Verde", ISO2: "CV"},
		"KY": Country{Name: "Cayman Islands", ISO2: "KY"},
		"CF": Country{Name: "Central African Republic", ISO2: "CF"},
		"TD": Country{Name: "Chad", ISO2: "TD"},
		"CL": Country{Name: "Chile", ISO2: "CL"},
		"CN": Country{Name: "China", ISO2: "CN"},
		"CX": Country{Name: "Christmas Island", ISO2: "CX"},
		"CC": Country{Name: "Cocos (Keeling) Islands", ISO2: "CC"},
		"CO": Country{Name: "Colombia", ISO2: "CO"},
		"KM": Country{Name: "Comoros", ISO2: "KM"},
		"CG": Country{Name: "Congo (Brazzaville)", ISO2: "CG"},
		"CD": Country{Name: "Congo (Kinshasa)", ISO2: "CD"},
		"CK": Country{Name: "Cook Islands", ISO2: "CK"},
		"CR": Country{Name: "Costa Rica", ISO2: "CR"},
		"HR": Country{Name: "Croatia", ISO2: "HR"},
		"CU": Country{Name: "Cuba", ISO2: "CU"},
		"CY": Country{Name: "Cyprus", ISO2: "CY"},
		"CZ": Country{Name: "Czech Republic", ISO2: "CZ"},
		"CI": Country{Name: "Côte d'Ivoire", ISO2: "CI"},
		"DK": Country{Name: "Denmark", ISO2: "DK"},
		"DJ": Country{Name: "Djibouti", ISO2: "DJ"},
		"DM": Country{Name: "Dominica", ISO2: "DM"},
		"DO": Country{Name: "Dominican Republic", ISO2: "DO"},
		"EC": Country{Name: "Ecuador", ISO2: "EC"},
		"EG": Country{Name: "Egypt", ISO2: "EG"},
		"SV": Country{Name: "El Salvador", ISO2: "SV"},
		"GQ": Country{Name: "Equatorial Guinea", ISO2: "GQ"},
		"ER": Country{Name: "Eritrea", ISO2: "ER"},
		"EE": Country{Name: "Estonia", ISO2: "EE"},
		"ET": Country{Name: "Ethiopia", ISO2: "ET"},
		"FK": Country{Name: "Falkland Islands (Malvinas)", ISO2: "FK"},
		"FO": Country{Name: "Faroe Islands", ISO2: "FO"},
		"FJ": Country{Name: "Fiji", ISO2: "FJ"},
		"FI": Country{Name: "Finland", ISO2: "FI"},
		"FR": Country{Name: "France", ISO2: "FR"},
		"GF": Country{Name: "French Guiana", ISO2: "GF"},
		"PF": Country{Name: "French Polynesia", ISO2: "PF"},
		"TF": Country{Name: "French Southern Territories", ISO2: "TF"},
		"GA": Country{Name: "Gabon", ISO2: "GA"},
		"GM": Country{Name: "Gambia", ISO2: "GM"},
		"GE": Country{Name: "Georgia", ISO2: "GE"},
		"DE": Country{Name: "Germany", ISO2: "DE"},
		"GH": Country{Name: "Ghana", ISO2: "GH"},
		"GI": Country{Name: "Gibraltar", ISO2: "GI"},
		"GR": Country{Name: "Greece", ISO2: "GR"},
		"GL": Country{Name: "Greenland", ISO2: "GL"},
		"GD": Country{Name: "Grenada", ISO2: "GD"},
		"GP": Country{Name: "Guadeloupe", ISO2: "GP"},
		"GU": Country{Name: "Guam", ISO2: "GU"},
		"GT": Country{Name: "Guatemala", ISO2: "GT"},
		"GG": Country{Name: "Guernsey", ISO2: "GG"},
		"GN": Country{Name: "Guinea", ISO2: "GN"},
		"GW": Country{Name: "Guinea-Bissau", ISO2: "GW"},
		"GY": Country{Name: "Guyana", ISO2: "GY"},
		"HT": Country{Name: "Haiti", ISO2: "HT"},
		"HM": Country{Name: "Heard and Mcdonald Islands", ISO2: "HM"},
		"VA": Country{Name: "Holy See (Vatican City State)", ISO2: "VA"},
		"HN": Country{Name: "Honduras", ISO2: "HN"},
		"HK": Country{Name: "Hong Kong, SAR China", ISO2: "HK"},
		"HU": Country{Name: "Hungary", ISO2: "HU"},
		"IS": Country{Name: "Iceland", ISO2: "IS"},
		"IN": Country{Name: "India", ISO2: "IN"},
		"ID": Country{Name: "Indonesia", ISO2: "ID"},
		"IR": Country{Name: "Iran, Islamic Republic of", ISO2: "IR"},
		"IQ": Country{Name: "Iraq", ISO2: "IQ"},
		"IE": Country{Name: "Ireland", ISO2: "IE"},
		"IM": Country{Name: "Isle of Man", ISO2: "IM"},
		"IL": Country{Name: "Israel", ISO2: "IL"},
		"IT": Country{Name: "Italy", ISO2: "IT"},
		"JM": Country{Name: "Jamaica", ISO2: "JM"},
		"JP": Country{Name: "Japan", ISO2: "JP"},
		"JE": Country{Name: "Jersey", ISO2: "JE"},
		"JO": Country{Name: "Jordan", ISO2: "JO"},
		"KZ": Country{Name: "Kazakhstan", ISO2: "KZ"},
		"KE": Country{Name: "Kenya", ISO2: "KE"},
		"KI": Country{Name: "Kiribati", ISO2: "KI"},
		"KP": Country{Name: "Korea (North)", ISO2: "KP"},
		"KR": Country{Name: "Korea (South)", ISO2: "KR"},
		"KW": Country{Name: "Kuwait", ISO2: "KW"},
		"KG": Country{Name: "Kyrgyzstan", ISO2: "KG"},
		"LA": Country{Name: "Lao PDR", ISO2: "LA"},
		"LV": Country{Name: "Latvia", ISO2: "LV"},
		"LB": Country{Name: "Lebanon", ISO2: "LB"},
		"LS": Country{Name: "Lesotho", ISO2: "LS"},
		"LR": Country{Name: "Liberia", ISO2: "LR"},
		"LY": Country{Name: "Libya", ISO2: "LY"},
		"LI": Country{Name: "Liechtenstein", ISO2: "LI"},
		"LT": Country{Name: "Lithuania", ISO2: "LT"},
		"LU": Country{Name: "Luxembourg", ISO2: "LU"},
		"MO": Country{Name: "Macao, SAR China", ISO2: "MO"},
		"MK": Country{Name: "Macedonia, Republic of", ISO2: "MK"},
		"MG": Country{Name: "Madagascar", ISO2: "MG"},
		"MW": Country{Name: "Malawi", ISO2: "MW"},
		"MY": Country{Name: "Malaysia", ISO2: "MY"},
		"MV": Country{Name: "Maldives", ISO2: "MV"},
		"ML": Country{Name: "Mali", ISO2: "ML"},
		"MT": Country{Name: "Malta", ISO2: "MT"},
		"MH": Country{Name: "Marshall Islands", ISO2: "MH"},
		"MQ": Country{Name: "Martinique", ISO2: "MQ"},
		"MR": Country{Name: "Mauritania", ISO2: "MR"},
		"MU": Country{Name: "Mauritius", ISO2: "MU"},
		"YT": Country{Name: "Mayotte", ISO2: "YT"},
		"MX": Country{Name: "Mexico", ISO2: "MX"},
		"FM": Country{Name: "Micronesia, Federated States of", ISO2: "FM"},
		"MD": Country{Name: "Moldova", ISO2: "MD"},
		"MC": Country{Name: "Monaco", ISO2: "MC"},
		"MN": Country{Name: "Mongolia", ISO2: "MN"},
		"ME": Country{Name: "Montenegro", ISO2: "ME"},
		"MS": Country{Name: "Montserrat", ISO2: "MS"},
		"MA": Country{Name: "Morocco", ISO2: "MA"},
		"MZ": Country{Name: "Mozambique", ISO2: "MZ"},
		"MM": Country{Name: "Myanmar", ISO2: "MM"},
		"NA": Country{Name: "Namibia", ISO2: "NA"},
		"NR": Country{Name: "Nauru", ISO2: "NR"},
		"NP": Country{Name: "Nepal", ISO2: "NP"},
		"AN": Country{Name: "Netherlands Antilles", ISO2: "AN"},
		"NL": Country{Name: "Netherlands", ISO2: "NL"},
		"NC": Country{Name: "New Caledonia", ISO2: "NC"},
		"NZ": Country{Name: "New Zealand", ISO2: "NZ"},
		"NI": Country{Name: "Nicaragua", ISO2: "NI"},
		"NE": Country{Name: "Niger", ISO2: "NE"},
		"NG": Country{Name: "Nigeria", ISO2: "NG"},
		"NU": Country{Name: "Niue", ISO2: "NU"},
		"NF": Country{Name: "Norfolk Island", ISO2: "NF"},
		"MP": Country{Name: "Northern Mariana Islands", ISO2: "MP"},
		"NO": Country{Name: "Norway", ISO2: "NO"},
		"OM": Country{Name: "Oman", ISO2: "OM"},
		"PK": Country{Name: "Pakistan", ISO2: "PK"},
		"PW": Country{Name: "Palau", ISO2: "PW"},
		"PS": Country{Name: "Palestinian Territory", ISO2: "PS"},
		"PA": Country{Name: "Panama", ISO2: "PA"},
		"PG": Country{Name: "Papua New Guinea", ISO2: "PG"},
		"PY": Country{Name: "Paraguay", ISO2: "PY"},
		"PE": Country{Name: "Peru", ISO2: "PE"},
		"PH": Country{Name: "Philippines", ISO2: "PH"},
		"PN": Country{Name: "Pitcairn", ISO2: "PN"},
		"PL": Country{Name: "Poland", ISO2: "PL"},
		"PT": Country{Name: "Portugal", ISO2: "PT"},
		"PR": Country{Name: "Puerto Rico", ISO2: "PR"},
		"QA": Country{Name: "Qatar", ISO2: "QA"},
		"RO": Country{Name: "Romania", ISO2: "RO"},
		"RU": Country{Name: "Russian Federation", ISO2: "RU"},
		"RW": Country{Name: "Rwanda", ISO2: "RW"},
		"RE": Country{Name: "Réunion", ISO2: "RE"},
		"SH": Country{Name: "Saint Helena", ISO2: "SH"},
		"KN": Country{Name: "Saint Kitts and Nevis", ISO2: "KN"},
		"LC": Country{Name: "Saint Lucia", ISO2: "LC"},
		"PM": Country{Name: "Saint Pierre and Miquelon", ISO2: "PM"},
		"VC": Country{Name: "Saint Vincent and Grenadines", ISO2: "VC"},
		"BL": Country{Name: "Saint-Barthélemy", ISO2: "BL"},
		"MF": Country{Name: "Saint-Martin (French part)", ISO2: "MF"},
		"WS": Country{Name: "Samoa", ISO2: "WS"},
		"SM": Country{Name: "San Marino", ISO2: "SM"},
		"ST": Country{Name: "Sao Tome and Principe", ISO2: "ST"},
		"SA": Country{Name: "Saudi Arabia", ISO2: "SA"},
		"SN": Country{Name: "Senegal", ISO2: "SN"},
		"RS": Country{Name: "Serbia", ISO2: "RS"},
		"SC": Country{Name: "Seychelles", ISO2: "SC"},
		"SL": Country{Name: "Sierra Leone", ISO2: "SL"},
		"SG": Country{Name: "Singapore", ISO2: "SG"},
		"SK": Country{Name: "Slovakia", ISO2: "SK"},
		"SI": Country{Name: "Slovenia", ISO2: "SI"},
		"SB": Country{Name: "Solomon Islands", ISO2: "SB"},
		"SO": Country{Name: "Somalia", ISO2: "SO"},
		"ZA": Country{Name: "South Africa", ISO2: "ZA"},
		"GS": Country{Name: "South Georgia and the South Sandwich Islands", ISO2: "GS"},
		"SS": Country{Name: "South Sudan", ISO2: "SS"},
		"ES": Country{Name: "Spain", ISO2: "ES"},
		"LK": Country{Name: "Sri Lanka", ISO2: "LK"},
		"SD": Country{Name: "Sudan", ISO2: "SD"},
		"SR": Country{Name: "Suriname", ISO2: "SR"},
		"SJ": Country{Name: "Svalbard and Jan Mayen Islands", ISO2: "SJ"},
		"SZ": Country{Name: "Swaziland", ISO2: "SZ"},
		"XK": Country{Name: "Republic of Kosovo", ISO2: "XK"},
		"SE": Country{Name: "Sweden", ISO2: "SE"},
		"CH": Country{Name: "Switzerland", ISO2: "CH"},
		"SY": Country{Name: "Syrian Arab Republic (Syria)", ISO2: "SY"},
		"TW": Country{Name: "Taiwan, Republic of China", ISO2: "TW"},
		"TJ": Country{Name: "Tajikistan", ISO2: "TJ"},
		"TZ": Country{Name: "Tanzania, United Republic of", ISO2: "TZ"},
		"TH": Country{Name: "Thailand", ISO2: "TH"},
		"TL": Country{Name: "Timor-Leste", ISO2: "TL"},
		"TG": Country{Name: "Togo", ISO2: "TG"},
		"TK": Country{Name: "Tokelau", ISO2: "TK"},
		"TO": Country{Name: "Tonga", ISO2: "TO"},
		"TT": Country{Name: "Trinidad and Tobago", ISO2: "TT"},
		"TN": Country{Name: "Tunisia", ISO2: "TN"},
		"TR": Country{Name: "Turkey", ISO2: "TR"},
		"TM": Country{Name: "Turkmenistan", ISO2: "TM"},
		"TC": Country{Name: "Turks and Caicos Islands", ISO2: "TC"},
		"TV": Country{Name: "Tuvalu", ISO2: "TV"},
		"UG": Country{Name: "Uganda", ISO2: "UG"},
		"UA": Country{Name: "Ukraine", ISO2: "UA"},
		"AE": Country{Name: "United Arab Emirates", ISO2: "AE"},
		"GB": Country{Name: "United Kingdom", ISO2: "GB"},
		"US": Country{Name: "United States of America", ISO2: "US"},
		"UY": Country{Name: "Uruguay", ISO2: "UY"},
		"UM": Country{Name: "US Minor Outlying Islands", ISO2: "UM"},
		"UZ": Country{Name: "Uzbekistan", ISO2: "UZ"},
		"VU": Country{Name: "Vanuatu", ISO2: "VU"},
		"VE": Country{Name: "Venezuela (Bolivarian Republic)", ISO2: "VE"},
		"VN": Country{Name: "Viet Nam", ISO2: "VN"},
		"VI": Country{Name: "Virgin Islands, US", ISO2: "VI"},
		"WF": Country{Name: "Wallis and Futuna Islands", ISO2: "WF"},
		"EH": Country{Name: "Western Sahara", ISO2: "EH"},
		"YE": Country{Name: "Yemen", ISO2: "YE"},
		"ZM": Country{Name: "Zambia", ISO2: "ZM"},
		"ZW": Country{Name: "Zimbabwe", ISO2: "ZW"},
	}

	countryTranslations = map[string]string{
		"Afeganistão":             "",
		"Akrotiri":                "",
		"Albânia":                 "",
		"Argélia":                 "",
		"Samoa Americana":         "",
		"Andorra":                 "",
		"Angola":                  "",
		"Anguilla":                "",
		"Antártica":               "",
		"Antígua e Barbuda":       "",
		"Argentina":               "",
		"Armênia":                 "",
		"Aruba":                   "",
		"Ilhas Ashmore e Cartier": "",
		"Austrália":               "",
		"Áustria":                 "",
		"Azerbaijão":              "",
		"Bahamas, The":            "",
		"Barém":                   "",
		"Bangladesh":              "",
		"Barbados":                "",
		"Bassas da India":         "",
		"Bielorrússia":            "",
		"Bélgica":                 "",
		"Belize":                  "",
		"Benin":                   "",
		"Bermudas":                "",
		"Butão":                   "",
		"Bolívia":                 "",
		"Bósnia e Herzegovina":    "",
		"Botsuana":                "",
		"Ilha Bouvet":             "",
		"Brasil":                  "",
		"Território Britânico do Oceano Índico": "",
		"Ilhas Virgens Britânicas":              "",
		"Brunei":                                "",
		"Bulgária":                              "",
		"Burkina Faso":                          "",
		"Birmânia":                              "",
		"Burundi":                               "",
		"Camboja":                               "",
		"Camarões":                              "",
		"Canadá":                                "",
		"cabo Verde":                            "",
		"Ilhas Cayman":                          "",
		"República Centro-Africana":             "",
		"Chade":                                 "",
		"Chile":                                 "",
		"China":                                 "",
		"Ilha do Natal":                         "",
		"Clipperton Island":                     "",
		"Ilhas Cocos (Keeling)":                 "",
		"Colômbia":                              "",
		"Comores":                               "",
		"Congo, República Democrática do":       "",
		"República do Congo":                    "",
		"Ilhas Cook":                            "",
		"Ilhas do Mar de Coral":                 "",
		"Costa Rica":                            "",
		"Costa do Marfim":                       "",
		"Croácia":                               "",
		"Cuba":                                  "",
		"Chipre":                                "",
		"República Checa":                       "",
		"Dinamarca":                             "",
		"Dhekelia":                              "",
		"Djibuti":                               "",
		"Dominica":                              "",
		"República Dominicana":                  "",
		"Equador":                               "",
		"Egito":                                 "",
		"El Salvador":                           "",
		"Guiné Equatorial":                      "",
		"Eritreia":                              "",
		"Estônia":                               "",
		"Etiópia":                               "",
		"Europa Island":                         "",
		"Ilhas Malvinas (Ilhas Malvinas)":       "",
		"ilhas Faroe":                           "",
		"Fiji":                                  "",
		"Finlândia":                             "",
		"França":                                "",
		"Guiana Francesa":                       "",
		"Polinésia Francesa":                    "",
		"Terras Austrais e Antárticas Francesas": "",
		"Gabão":                            "",
		"Gâmbia, The":                      "",
		"faixa de Gaza":                    "",
		"Geórgia":                          "",
		"Alemanha":                         "",
		"Gana":                             "",
		"Gibraltar":                        "",
		"Ilhas Glorioso":                   "",
		"Grécia":                           "",
		"Gronelândia":                      "",
		"Granada":                          "",
		"Guadalupe":                        "",
		"Guam":                             "",
		"Guatemala":                        "",
		"Guernsey":                         "",
		"Guiné":                            "",
		"Guiné-Bissau":                     "",
		"Guiana":                           "",
		"Haiti":                            "",
		"Ilha Heard e Ilhas McDonald":      "",
		"Santa Sé (Cidade do Vaticano)":    "",
		"Honduras":                         "",
		"Hong Kong":                        "",
		"Hungria":                          "",
		"Islândia":                         "",
		"Índia":                            "",
		"Indonésia":                        "",
		"Eu corri":                         "",
		"Iraque":                           "",
		"Irlanda":                          "",
		"Ilha de Man":                      "",
		"Israel":                           "",
		"Itália":                           "",
		"Jamaica":                          "",
		"Jan Mayen":                        "",
		"Japão":                            "",
		"Jersey":                           "",
		"Jordânia":                         "",
		"Ilha Juan de Nova":                "",
		"Cazaquistão":                      "",
		"Quênia":                           "",
		"Kiribati":                         "",
		"Coreia do Norte":                  "",
		"Coreia do Sul":                    "",
		"Kuwait":                           "",
		"Quirguistão":                      "",
		"Laos":                             "",
		"Letônia":                          "",
		"Líbano":                           "",
		"Lesoto":                           "",
		"Libéria":                          "",
		"Líbia":                            "",
		"Liechtenstein":                    "",
		"Lituânia":                         "",
		"Luxemburgo":                       "",
		"Macau":                            "",
		"Macedônia":                        "",
		"Madagáscar":                       "",
		"Malawi":                           "",
		"Malásia":                          "",
		"Maldivas":                         "",
		"Mali":                             "",
		"Malta":                            "",
		"Ilhas Marshall":                   "",
		"Martinica":                        "",
		"Mauritânia":                       "",
		"Maurícia":                         "",
		"Mayotte":                          "",
		"México":                           "",
		"Micronésia, Estados Federados da": "",
		"Moldova":                          "",
		"Mônaco":                           "",
		"Mongólia":                         "",
		"Montserrat":                       "",
		"Marrocos":                         "",
		"Moçambique":                       "",
		"Namíbia":                          "",
		"Nauru":                            "",
		"Ilha Navassa":                     "",
		"Nepal":                            "",
		"Países Baixos":                    "",
		"Antilhas Holandesas":              "",
		"Nova Caledônia":                   "",
		"Nova Zelândia":                    "",
		"Nicarágua":                        "",
		"Níger":                            "",
		"Nigéria":                          "",
		"Niue":                             "",
		"Ilha Norfolk":                     "",
		"Ilhas Marianas do Norte":          "",
		"Noruega":                          "",
		"Omã":                              "",
		"Paquistão":                        "",
		"Palau":                            "",
		"Panamá":                           "",
		"Papua Nova Guiné":                 "",
		"Ilhas Paracel":                    "",
		"Paraguai":                         "",
		"Peru":                             "",
		"Filipinas":                        "",
		"Ilhas Pitcairn":                   "",
		"Polônia":                          "",
		"Portugal":                         "",
		"Porto Rico":                       "",
		"Catar":                            "",
		"Reunião":                          "",
		"Romênia":                          "",
		"Rússia":                           "",
		"Ruanda":                           "",
		"Santa Helena":                     "",
		"São Cristóvão e Nevis":            "",
		"Santa Lúcia":                      "",
		"São Pedro e Miquelon":             "",
		"São Vicente e Granadinas":         "",
		"Samoa":                            "",
		"San Marino":                       "",
		"São Tomé e Príncipe":              "",
		"Arábia Saudita":                   "",
		"Senegal":                          "",
		"Sérvia e Montenegro":              "",
		"Seychelles":                       "",
		"Serra Leoa":                       "",
		"Cingapura":                        "",
		"Eslováquia":                       "",
		"Eslovênia":                        "",
		"Ilhas Salomão":                    "",
		"Somália":                          "",
		"África do Sul":                    "",
		"Ilhas Geórgia do Sul e Sandwich do Sul": "",
		"Espanha":                "",
		"Ilhas Spratly":          "",
		"Sri Lanka":              "",
		"Sudão":                  "",
		"Suriname":               "",
		"Svalbard":               "",
		"Suazilândia":            "",
		"Suécia":                 "",
		"Suíça":                  "",
		"Síria":                  "",
		"Taiwan":                 "",
		"Tajiquistão":            "",
		"Tanzânia":               "",
		"Tailândia":              "",
		"Timor-Leste":            "",
		"Ir":                     "",
		"Tokelau":                "",
		"Tonga":                  "",
		"Trindade e Tobago":      "",
		"Ilha de Tromelin":       "",
		"Tunísia":                "",
		"Turquemenistão":         "",
		"Ilhas Turcas e Caicos":  "",
		"Tuvalu":                 "",
		"Uganda":                 "",
		"Ucrânia":                "",
		"Emirados Árabes Unidos": "",
		"Reino Unido":            "",
		"Estados Unidos":         "",
		"Uruguai":                "",
		"Usbequistão":            "",
		"Vanuatu":                "",
		"Venezuela":              "",
		"Vietnã":                 "",
		"Ilhas Virgens":          "",
		"Ilha Wake":              "",
		"Wallis e Futuna":        "",
		"Cisjordânia":            "",
		"Saara Ocidental":        "",
		"Iémen":                  "",
		"Zâmbia":                 "",
		"Zimbábue":               "",
	}
)
